### ISSUE TITLE
Requests for dataset metioned in paper

### ISSUE THREAD

**Issue by yeren66** [mosabrezaei/Test-Case-Recommendation#1]
In the paper, it was mentioned that to support test case generation, the methods2test dataset was utilized and cleaned, filtering down from 577,611 entries to 4,500 clean samples. However, I am confused about the figure of 577,611 since the methods2test dataset contains a total of 780,944 entries. Additionally, I couldn't find this data on GitHub. Could you please share this dataset? I would be very grateful.

**Comment by mosabrezaei** [comment]
Hi Yeren,
I have just updated the GitHub repository with the extracted methods and tests from the methods2test dataset that we used in this work.

**Comment by yeren66** [comment]
Thanks!🙏
